# Generated by Django 4.0.3 on 2022-03-11 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_module_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=34)),
                ('password', models.CharField(max_length=34)),
            ],
        ),
        migrations.AlterField(
            model_name='module',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.module')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.student')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.professor')),
            ],
        ),
    ]
