# Generated by Django 4.0.3 on 2022-03-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_alter_module_year_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='student',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
